CARGAR_PANTALLA_INICIAL:
    PUSH DE: PUSH HL: PUSH BC: PUSH AF

    LD DE, $4000
    LD HL, PANTALLA_INICIAL
    LD BC, $5B00 - $4000
    CALL CPANT_BUCLE

; CARGAR_PANTALLA_ADIOS:
;     PUSH DE: PUSH HL: PUSH BC: PUSH AF

;     LD DE, $4000
;     LD HL, PANTALLA_INICIAL
;     LD BC, $5B00 - $4000
;     CALL CPANT_BUCLE

; CARGAR_PANTALLA_FIN:
;     PUSH DE: PUSH HL: PUSH BC: PUSH AF

;     LD DE, $4000
;     LD HL, PANTALLA_INICIAL
;     LD BC, $5B00 - $4000

CPANT_BUCLE:
    LDIR
    POP AF: POP BC: POP HL: POP DE
    RET

PANTALLA_INICIAL: INCBIN "connect4screen.SCR"
