; STRINGS PARA IMPRESION

STRING_FILA_VACIA_B: DB "                        ", 0
STRING_BIENVENIDA: DB " Bienvenido a Conecta 4 ", 0
STRING_JUGAR: DB " Quieres jugar? S/N:   ", 0
STRING_FILA_VACIA_J: DB "                       ", 0
STRING_FILA_VACIA_A: DB "            ", 0
STRING_ADIOS: DB "  ADIOS!!!! ", 0
STRING_FIN: DB " LA PARTIDA HA FINALIZADO ", 0
STRING_OTRA: DB " QUIERES JUGAR OTRA VEZ? S/N:   ", 0
CHAR_CARACTER: DB 0, 0

; PANTALLA DE INICIO
PANTALLA_BIENVENIDA: INCBIN "connect4screen.SCR"
    INCLUDE "pantalla_juego.asm"

GB_BIENVENIDA:
    PUSH DE: PUSH HL: PUSH BC: PUSH AF

    LD DE, $4000
    LD HL, PANTALLA_BIENVENIDA
    LD BC, $5B00 - $4000
BIENVENIDA_BUCLE:
    LDIR
PRINT_BIENVENIDA:
    LD B, 1
    LD C, 4
    LD IX, STRING_FILA_VACIA_B
    CALL PRINTAT
    LD B, 3
    LD IX, STRING_FILA_VACIA_B
    CALL PRINTAT
    LD B, 2
    LD A, COLOR_TEXTO_ROJO
    LD IX, STRING_BIENVENIDA
    CALL PRINTAT

    LD B, 20
    LD C, 9
    LD IX, STRING_FILA_VACIA_J
    CALL PRINTAT
    LD B, 22
    LD IX, STRING_FILA_VACIA_J
    CALL PRINTAT
    LD B, 21
    LD A, COLOR_TEXTO_AMARILLO
    LD IX, STRING_JUGAR
    CALL PRINTAT
    LD A, BLINK + 8*COLOR_TEXTO_AMARILLO

GB_BLINKER_JUGAR:
    LD B, 21
    LD C, 30
    LD HL, $5800 + 21*NUM_COLS + 30
    LD (HL), A
    POP AF: POP BC: POP HL: POP DE

    RET    

GB_PRINT_CHAR_SON:
    LD B, 21
    LD C, 30
    LD IX, CHAR_CARACTER
    CALL PRINTAT

    RET

GB_ADIOS:
    CALL PTLLA_NEGRA
PRINT_ADIOS:
    LD B, 10
    LD C, 10
    LD A, 8*COLOR_TEXTO_ROJO
    LD IX, STRING_FILA_VACIA_A
    CALL PRINTAT
    LD B, 12
    LD A, 8*COLOR_TEXTO_ROJO
    LD IX, STRING_FILA_VACIA_A
    CALL PRINTAT
    LD B, 11
    LD A, 8*COLOR_TEXTO_ROJO
    LD IX, STRING_ADIOS
    CALL PRINTAT

    RET

GB_FIN_NEXT:
    CALL PTLLA_NEGRA
PRINT_FIN:
    LD B, 15
    LD C, 3
    LD A, 8*COLOR_TEXTO_ROJO
    LD IX, STRING_FIN
    CALL PRINTAT
    LD B, 21
    LD C, 0
    LD A, 8*COLOR_TEXTO_ROJO
    LD IX, STRING_OTRA
    CALL PRINTAT
        LD A, BLINK + 8*COLOR_TEXTO_ROJO
    CALL GB_BLINKER_JUGAR
    RET

GB_PTLLA_INICIO_DE_JUEGO:
    CALL PTLLA_NEGRA
    CALL SCR_PTLLA_JUEGO
    RET

PTLLA_NEGRA:
    PUSH BC: PUSH DE: PUSH HL: PUSH AF

    LD   HL,$5800
    LD   DE,$5801
    LD   (HL),0
    LD   BC,768-1
    LDIR

    POP AF: POP HL: POP DE: POP BC
    RET