GC_COLOR_JUGADOR_ACTUAL:
    LD A, D
    ADD BLINK
    LD HL, $5845
    PUSH HL
    CALL INC_HL_3X3
    CALL INC_HL_3X3
    CALL INC_HL_3X3
    POP HL
    RET
; SET_C_COLOR_R:
;     LD A, 1*8+2
;     CALL INC_HL_3X3
;     CALL INC_HL_3X3
;     CALL INC_HL_3X3
;     RET

GC_LEFT:
    PUSH HL: PUSH BC: PUSH AF: PUSH DE
    LD A, NEGRO
    PUSH HL
    CALL INC_HL_3X3
    CALL INC_HL_3X3
    CALL INC_HL_3X3
    POP HL
    LD BC, $FFFD
    ADD HL, BC
    LD A, D
    ADD BLINK
    PUSH HL
    CALL INC_HL_3X3
    CALL INC_HL_3X3
    CALL INC_HL_3X3
    POP HL
    POP DE: POP AF: POP BC: POP HL

    RET

GC_RIGHT:
    PUSH HL: PUSH BC: PUSH AF
    LD A, NEGRO
    PUSH HL
    CALL INC_HL_3X3
    CALL INC_HL_3X3
    CALL INC_HL_3X3
    POP HL
    LD BC, $3
    ADD HL, BC
    LD A, D
    ADD BLINK 
    PUSH HL
    CALL INC_HL_3X3
    CALL INC_HL_3X3
    CALL INC_HL_3X3
    POP HL
    POP AF: POP BC: POP HL

    RET
GC_ENTER:
; SET_C_COLOR_Y: ; LA RUTINA CAMBIA EL COLOR DE UN DETERMINADO BLOQUE 3X3 A AMARILLO
;     LD A, 1*8+6
;     CALL INC_HL_3X3
;     CALL INC_HL_3X3
;     CALL INC_HL_3X3
;     RET

; ; SET_PRED ; Rutina para indicar que el jugador actual es el rojo
; ;     LD HL, $5845
; ;     LD A, 2
; ;     CALL INC_HL_3X3
; ;     CALL INC_HL_3X3
; ;     CALL INC_HL_3X3
; ;     LD HL, $5845
; ;     CALL CONVERT_58_2_40
; ;     CALL DRAW_CIRCLE
; ;     RET

; ; SET_PYEL ; Rutina para indicar que el jugador actual es el amarillo
; ;     LD HL, $5857
; ;     LD A, 6
; ;     CALL INC_HL_3X3
; ;     CALL INC_HL_3X3
; ;     CALL INC_HL_3X3
; ;     LD HL, $5857
; ;     CALL CONVERT_58_2_40
; ;     CALL DRAW_CIRCLE
; ;     RET
GC_DRAW_CIRCLES_TOP:
    PUSH HL: PUSH AF: PUSH BC
    LD HL, $5845
    PUSH HL
    LD A, 0
    LD B, 7
DRAW_BLANK_CIRCLE:
    PUSH BC: PUSH HL
    CALL INC_HL_3X3
    CALL INC_HL_3X3
    CALL INC_HL_3X3
    POP HL: POP BC
    DJNZ DRAW_BLANK_CIRCLE
    POP HL

    CALL CONVERT_58_2_40
    CALL DRAW_CIRCLE_ROW

    POP BC: POP AF: POP HL

    RET
