PANTALLA_BIENVENIDA: INCBIN "connect4screen.SCR"
    INCLUDE "pantalla_juego.asm"

GB_BIENVENIDA:
    PUSH DE: PUSH HL: PUSH BC: PUSH AF

    LD DE, $4000
    LD HL, PANTALLA_BIENVENIDA
    LD BC, $5B00 - $4000
BIENVENIDA_BUCLE:
    LDIR
    POP AF: POP BC: POP HL: POP DE
    RET

GB_ADIOS:
    CALL PTLLA_NEGRA
    RET

GB_FIN_NEXT:
    CALL PTLLA_NEGRA
    RET

GB_PTLLA_INICIO_DE_JUEGO:
    CALL PTLLA_NEGRA
    CALL SCR_PTLLA_JUEGO
    RET


PTLLA_NEGRA:
    PUSH BC: PUSH DE: PUSH HL: PUSH AF

    LD   HL,$5800
    LD   DE,$5801
    LD   (HL),0
    LD   BC,768-1
    LDIR

    POP AF: POP HL: POP DE: POP BC
    RET

