LF_ESPERAR:
    PUSH BC
    PUSH AF
    LD BC, CONTADOR
LF_ESPERAR1: 
    DEC BC ; 6C
    LD A, B ; 4C
    OR C ; 4C
    NOP ; 4C
    JR NZ, LF_ESPERAR1 ; 12C
    ; DURACION TOTAL = APPROX 0,49 SEG
    POP AF
    POP BC
    RET
LF_INICIALIZACION:
    LD D, PLAYER2
    CALL GC_DRAW_CIRCLES_TOP
    RET
LF_SWITCH_JUGADOR:
    LD A, D
    CP PLAYER2
    JR Z, SET_P1
    CP PLAYER1
    JR Z, SET_P2
    RET
SET_P1:
    LD D, PLAYER1
    RET
SET_P2:
    LD D, PLAYER2
    RET
