    DEVICE ZXSPECTRUM48
    ORG $8000
    LD SP, 0
    LD A, 0 ; VALOR INICIAL DE A
    OUT ($FE), A ; COLOREA EL MARCO DE LA PANTALLA NEGRO
    JP INICIO
CONTADOR EQU 255
    INCLUDE "cargarPantalla.asm"
    INCLUDE "quieresJugar.asm"
    INCLUDE "pantallaJuego.asm"
    INCLUDE "pantallasSimples.asm"

INICIO:
    CALL BIENVENIDA_JUEGO
JUEGO:
    CALL PARTIDA
    CALL JUEGO

JUGAR_PARTIDA:

FIN: HALT

BIENVENIDA_JUEGO:
    CALL CARGAR_PANTALLA_INICIAL
    CALL MENSAJE_BIENVENIDA

    ; GESTIONAR RESPUESTA (SI O NO)
    RET

ADIOS:
    CALL PTLLA_NEGRA
    CALL PTLLA_ADIOS
    JR FIN

PARTIDA:
    CALL PTLLA_NEGRA
    LD HL, $0405
    CALL COORD_ATRIB
    CALL PTLLA_JUEGO
    JR FIN

COORD_ATRIB:
; PREREQUISITO: HABER SELECCIONADO UNA FILA Y UNA COLUMNA (H Y L) SOBRE LA QUE SE QUIERE OBTENER UNA DIRECCIÓN VIDEORAM
; H = FILA
; L = COLUMNA
; HL = DIRECCIÓN DE LA VIDEORAM

    PUSH AF
    LD A, H ; 0 0 0 H4 H3 H2 H1 H0
    SLA A: SLA A: SLA A: SLA A: SLA A ; H2 H1 H0 0 0 0 0 0
    OR L ; H2 H1 H0 L4 L3 L2 L1 L0
    LD A, H ; 0 0 0 H4 H3 H2 H1 H0
    SRA A: SRA A: SRA A; 0 0 0 0 0 0 H4 H3 
    OR $58 ; 0 1 0 1 1 0 H4 H3
    ; HL = 0 1 0 1 1 0 H4 H3 H2 H1 H0 L4 L3 L2 L1 L0
    POP AF
    RET

COORD_ATRIB_PXLS: ; DEVUELVE LA DIRECCION A LA PRIMERA FILA DE 8 PIXELS DEL BLOQUE INDICADO POR FILA Y COLUMNA

    PUSH AF: PUSH BC
    LD A, H ; 0 0 0 H4 H3 H2 H1 H0
    SLA A: SLA A: SLA A: SLA A: SLA A ; H2 H1 H0 0 0 0 0 0
    OR L ; H2 H1 H0 L4 L3 L2 L1 L0
    LD A, H ; 0 0 0 H4 H3 H2 H1 H0
    SRA A: SRA A: SRA A ; 0 0 0 0 0 0 H4 H3 
    OR $58 ; 0 1 0 1 1 0 H4 H3
    ; HL = 0 1 0 1 1 0 H4 H3 H2 H1 H0 L4 L3 L2 L1 L0
    LD BC, $E800
    ADD HL, BC
    POP BC: POP AF
    RET


; COORD_ATRIB_TABLERO:
;     ; PREREQUISITO: HABER PASADO UNA COORDENADA HL (FILA COLUMNA) POR COORD_ATRIB
;     ; + 4*32 + 5
;     ADD HL, %10000101 ; COORD ESTANDARIZADA A QUE EL TABLERO INICIA EN LA FILA 4, COL 5
;     RET

; COORD_ATRIB_JUGADOR:
;     ; PREREQUISITO: HABER PASADO UNA COORDENADA HL (FILA COLUMNA) POR COORD_ATRIB
;     ; + 32 + 5
;     ADD HL, %00100101 ; COORD ESTANDARIZADA A QUE EL INDICADOR DE JUGADOR INICIA EN LA FILA 1, COL 5
;     RET

; PINTAR_FICHA_R:
;     CALL COORD_ATRIB
;     CALL COORD_ATRIB_TABLERO
;     CALL SET_C_COLOR_R
;     RET

; PINTAR_FICHA_Y:
;     CALL COORD_ATRIB
;     CALL COORD_ATRIB_TABLERO
;     CALL SET_C_COLOR_y
;     RET

ESPERAR:
    PUSH BC
    PUSH AF
    LD BC, CONTADOR
ESPERAR1: 
    DEC BC ; 6C
    LD A, B ; 4C
    OR C ; 4C
    NOP ; 4C
    JR NZ, ESPERAR1 ; 12C
    ; DURACION TOTAL = APPROX 0,49 SEG
    POP AF
    POP BC
    RET
    
RET
