    DEVICE ZXSPECTRUM48
    ORG $8000
    LD SP, 0
    LD A, 0 ; VALOR INICIAL DE A
    OUT ($FE), A ; COLOREA EL MARCO DE LA PANTALLA NEGRO
    JP INICIO

; CONSTANTES
CONTADOR EQU 255
NUM_FILAS EQU 24
NUM_COLS EQU 32

COLOR_TEXTO_AZUL EQU 1
COLOR_TEXTO_ROJO EQU 2
COLOR_TEXTO_AMARILLO EQU 6
BLINK EQU 128

; INCLUDES
    INCLUDE "colors.asm"
    INCLUDE "graphics_basic.asm"
    INCLUDE "graphics_core.asm"
    INCLUDE "keyboard.asm"
    INCLUDE "logic_checks.asm"
    INCLUDE "logic_flow.asm"
    INCLUDE "variables.asm"
    INCLUDE "printat.asm"

; STRINGS PARA IMPRESION

STRING_FILA_VACIA_B: DB "                        ", 0
STRING_BIENVENIDA: DB " Bienvenido a Conecta 4 ", 0
STRING_JUGAR: DB " Quieres jugar? S/N:   ", 0
STRING_FILA_VACIA_J: DB "                       ", 0
STRING_FILA_VACIA_A: DB "            ", 0
STRING_ADIOS: DB "  ADIOS!!!! ", 0
STRING_FIN: DB " LA PARTIDA HA FINALIZADO ", 0
STRING_OTRA: DB "QUIERES JUGAR OTRA VEZ? S/N: ", 0
CHAR_CARACTER: DB 0, 0

; INICIO DEL FLUJO DEL PROGRAMA FUNCIONAL
INICIO:
    CALL GB_BIENVENIDA
    CALL PRINT_BIENVENIDA
    CALL BLINKER_JUGAR
    CALL K_SON
    LD A, D
    LD (CHAR_CARACTER), A
    LD A, COLOR_TEXTO_AMARILLO
    CALL PRINT_CHAR_SON
    LD A, (CHAR_CARACTER)
    CP 'S'
    CALL Z, LOGICA_JUEGO
    CP 'N'
    CALL Z, ADIOS

ADIOS:
    CALL GB_ADIOS
    CALL PRINT_ADIOS
FINAL:
    LD B, 10
    CALL ESPERAR
    DJNZ FINAL
    HALT

FIN_NEXT: ; TERMINO LA PARTIDA, OFRECEMOS OTRA O FINALIZAR
    CALL GB_FIN_NEXT
    CALL K_SON
    LD A, D
    CP 'S'
    CALL Z, LOGICA_JUEGO
    CP 'N'
    CALL Z, ADIOS

LOGICA_JUEGO:
    CALL GB_PTLLA_INICIO_DE_JUEGO
    HALT
    CALL LF_INICIALIZACION
BUCLE_JUEGO:
    CALL LF_SWITCH_JUGADOR
GESTIONAR_JUGADA:
    CALL GC_COLOR_JUGADOR_ACTUAL
    CALL K_LR_ENTER
    CALL LC_VALIDPLAY
    ; SI SE DETECTO LEFT
    ; CALL (CONDICION DE DETECCION), GC_LEFT
    ; SI SE DETECTO RIGHT
    ; CALL (CONDICION DE DETECCION), GC_RIGHT
    ; SI SE DETECTO ENTER
    ; CALL (CONDICION DE DETECCION), GC_ENTER
COMPROBAR_FIN_JUEGO:
    CALL LC_COMPROBAR_FIN
    ; SI SE DETECTO EL FIN DEL JUEGO
    ; JR (CONDICION DE FIN), FIN_NEXT
    ; SI SE DETECTA QUE EL JUEGO SIGUE
    JR Z, FIN_NEXT
    JR BUCLE_JUEGO

ESPERAR:
    PUSH BC
    PUSH AF
    LD BC, CONTADOR
ESPERAR1: 
    DEC BC ; 6C
    LD A, B ; 4C
    OR C ; 4C
    NOP ; 4C
    JR NZ, ESPERAR1 ; 12C
    ; DURACION TOTAL = APPROX 0,49 SEG
    POP AF
    POP BC
    RET

COORD_ATRIB:
    ; PREREQUISITO: HABER SELECCIONADO UNA FILA Y UNA COLUMNA (H Y L) SOBRE LA QUE SE QUIERE OBTENER UNA DIRECCIÓN VIDEORAM
    ; H = FILA
    ; L = COLUMNA
    ; HL = DIRECCIÓN DE LA VIDEORAM

    PUSH AF
    LD A, H ; 0 0 0 H4 H3 H2 H1 H0
    SLA A: SLA A: SLA A: SLA A: SLA A ; H2 H1 H0 0 0 0 0 0
    OR L ; H2 H1 H0 L4 L3 L2 L1 L0
    LD A, H ; 0 0 0 H4 H3 H2 H1 H0
    SRA A: SRA A: SRA A; 0 0 0 0 0 0 H4 H3 
    OR $58 ; 0 1 0 1 1 0 H4 H3
    ; HL = 0 1 0 1 1 0 H4 H3 H2 H1 H0 L4 L3 L2 L1 L0
    POP AF
    RET

PRINT_BIENVENIDA:
    LD B, 1
    LD C, 4
    LD IX, STRING_FILA_VACIA_B
    CALL PRINTAT
    LD B, 3
    LD IX, STRING_FILA_VACIA_B
    CALL PRINTAT
    LD B, 2
    LD A, COLOR_TEXTO_ROJO
    LD IX, STRING_BIENVENIDA
    CALL PRINTAT

    LD B, 20
    LD C, 1
    LD IX, STRING_FILA_VACIA_J
    CALL PRINTAT
    LD B, 22
    LD IX, STRING_FILA_VACIA_J
    CALL PRINTAT
    LD B, 21
    LD A, COLOR_TEXTO_AMARILLO
    LD IX, STRING_JUGAR
    CALL PRINTAT

    RET

BLINKER_JUGAR:
    LD B, 21
    LD C, 17
    LD HL, $5800 + 21*NUM_COLS + 22
    LD A, BLINK + 8*COLOR_TEXTO_AMARILLO
    LD (HL), A

    RET

PRINT_CHAR_SON:
    LD B, 21
    LD C, 22
    LD IX, CHAR_CARACTER
    CALL PRINTAT

    RET

PRINT_ADIOS:
    
    LD B, 10
    LD C, 10
    LD A, 8*COLOR_TEXTO_ROJO
    LD IX, STRING_FILA_VACIA_A
    CALL PRINTAT
    LD B, 12
    LD A, 8*COLOR_TEXTO_ROJO
    LD IX, STRING_FILA_VACIA_A
    CALL PRINTAT
    LD B, 11
    LD A, 8*COLOR_TEXTO_ROJO
    LD IX, STRING_ADIOS
    CALL PRINTAT

    RET

PRINT_FIN:
