PTLLA_NEGRA:
    PUSH BC: PUSH DE: PUSH HL: PUSH AF
PTLLA_NEGRA_BUCLE:
    LD A, 0
    LD HL, $5800
    LD BC, $5B00 - $5800
    LD (HL), A
    INC HL
    DEC BC
    JR NZ, PTLLA_NEGRA_BUCLE
    JR VOLVER

PTLLA_ADIOS:
    LD A, 2*8
    LD B, 11
    LD C, 4
    LD IX, ADIOS
    CALL PRINTAT
    JR VOLVER

PTLLA_FIN:
    CALL PTLLA_NEGRA
    LD A, 1
    LD B, 1
    LD C, 2
    LD IX, FIN
    CALL PRINTAT
    LD A, 6
    LD B, 11
    LD C, 1
    LD IX, OTRA

    LD A, 128 + 8*COLOR
    LD($5800 + 11*32 + 30), A
    CALL S_N
    LD (CARACTER), A
    LD D, A
    LD A, COLOR
    LD B, 11
    LD C, 30
    LD IX, CARACTER
    CALL PRINTAT
    LD A, D
    JR VOLVER

VOLVER:
    LD (HL), A
    POP AF: POP HL: POP DE: POP BC
    RET

AZUL EQU 1
ROJO EQU 2
AMARILLO EQU 6
ADIOS: DB " ADIOS!!!! ", 0
FIN: DB " LA PARTIDA HA FINALIZADO ", 0
OTRA: DB "QUIERES JUGAR OTRA PARTIDA?", 0
CARACTER: DB 0, 0

    INCLUDE "PRINTAT.ASM"