SCR_PTLLA_JUEGO:
    PUSH BC: PUSH HL: PUSH DE: PUSH AF
    LD A, 0
    ; LD HL, $0405
    ; CALL COORD_ATRIB
    LD HL, $58A5
    CALL SET_GRID_EMPTY
    LD HL, $40A5
    CALL DRAW_EMPTY_CIRCLES
    POP AF: POP DE: POP HL: POP BC
    RET

SET_GRID_EMPTY:
    CALL SET_COLUMN_COLOR
    CALL SET_COLUMN_COLOR
    CALL SET_COLUMN_COLOR
    CALL SET_COLUMN_COLOR
    CALL SET_COLUMN_COLOR
    CALL SET_COLUMN_COLOR
    CALL SET_COLUMN_COLOR
    RET

DRAW_EMPTY_CIRCLES:
    CALL DRAW_CIRCLE_COLUMN
    CALL DRAW_CIRCLE_COLUMN
    CALL DRAW_CIRCLE_COLUMN
    CALL DRAW_CIRCLE_COLUMN
    CALL DRAW_CIRCLE_COLUMN
    CALL DRAW_CIRCLE_COLUMN
    CALL DRAW_CIRCLE_COLUMN
    CALL DRAW_CIRCLE_COLUMN
    RET

DRAW_CIRCLE_ROW:
    PUSH HL
    CALL DRAW_CIRCLE
    POP HL: INC HL: INC HL: INC HL: PUSH HL
    CALL DRAW_CIRCLE
    POP HL: INC HL: INC HL: INC HL: PUSH HL
    CALL DRAW_CIRCLE
    POP HL: INC HL: INC HL: INC HL: PUSH HL
    CALL DRAW_CIRCLE
    POP HL: INC HL: INC HL: INC HL: PUSH HL
    CALL DRAW_CIRCLE
    POP HL: INC HL: INC HL: INC HL: PUSH HL
    CALL DRAW_CIRCLE
    POP HL: INC HL: INC HL: INC HL: PUSH HL
    CALL DRAW_CIRCLE
    POP HL
    RET

DRAW_CIRCLE_COLUMN:
    CALL DRAW_CIRCLE
    CALL DRAW_CIRCLE
    CALL DRAW_CIRCLE
    CALL DRAW_CIRCLE
    CALL DRAW_CIRCLE
    CALL DRAW_CIRCLE
    LD BC, $EFC3
    ADD HL, BC
    RET

VERIFY_4000:
    LD A, $41
    CP H 
    CALL Z, SET_4800
    LD A, $49
    CP H
    CALL Z, SET_5000
    RET

SET_4800:
    LD H, $48
    RET

SET_5000:
    LD H, $50
    RET

SET_COLUMN_COLOR:
    CALL SET_C_COLOR_E
    CALL SET_C_COLOR_E
    CALL SET_C_COLOR_E
    CALL SET_C_COLOR_E
    CALL SET_C_COLOR_E
    CALL SET_C_COLOR_E
    LD BC, $FDC3
    ADD HL, BC
    RET

DRAW_CIRCLE:
    PUSH BC 
    LD BC, $001D

    CALL UL_CIRCLE
    CALL UM_CIRCLE
    CALL UR_CIRCLE
    
    ADD HL, BC
    CALL VERIFY_4000

    CALL ML_CIRCLE
    CALL MM_CIRCLE
    CALL MR_CIRCLE

    ADD HL, BC
    CALL VERIFY_4000

    CALL LL_CIRCLE
    CALL LM_CIRCLE
    CALL LR_CIRCLE
    
    ADD HL, BC
    CALL VERIFY_4000
    POP BC 
    
    RET

UL_CIRCLE:
    LD A, %00000000
    LD (HL), A
    CALL INC_AND_LOAD_H
    LD A, %00000011
    CALL INC_AND_LOAD_H
    LD A, %00000111
    CALL INC_AND_LOAD_H
    LD A, %00001111
    CALL INC_AND_LOAD_H
    LD A, %00011111
    CALL INC_AND_LOAD_H
    LD A, %00111111
    CALL INC_AND_LOAD_H
    CALL INC_AND_LOAD_H
    CALL SETBACK_HL
    RET

UM_CIRCLE:
    LD A, %00000000
    DEC H
    CALL INC_AND_LOAD_H
    LD A, %01111110
    CALL INC_AND_LOAD_H
    LD A, %11111111
    CALL INC_AND_LOAD_H
    CALL INC_AND_LOAD_H
    CALL INC_AND_LOAD_H
    CALL INC_AND_LOAD_H
    CALL INC_AND_LOAD_H
    CALL INC_AND_LOAD_H
    CALL SETBACK_HL
    RET

UR_CIRCLE:
    LD A, %00000000
    LD (HL), A
    CALL INC_AND_LOAD_H
    LD A, %11000000
    CALL INC_AND_LOAD_H
    LD A, %11100000
    CALL INC_AND_LOAD_H
    LD A, %11110000
    CALL INC_AND_LOAD_H
    LD A, %11111000
    CALL INC_AND_LOAD_H
    LD A, %11111100
    CALL INC_AND_LOAD_H
    CALL INC_AND_LOAD_H
    CALL SETBACK_HL
    RET

ML_CIRCLE:
    LD A, %00111111
    DEC H
    CALL INC_AND_LOAD_H
    LD A, %01111111
    CALL INC_AND_LOAD_H
    CALL INC_AND_LOAD_H
    CALL INC_AND_LOAD_H
    CALL INC_AND_LOAD_H
    CALL INC_AND_LOAD_H
    CALL INC_AND_LOAD_H
    LD A, %00111111
    CALL INC_AND_LOAD_H
    CALL SETBACK_HL
    RET

MM_CIRCLE:
    LD A, %11111111
    DEC H
    CALL INC_AND_LOAD_H
    CALL INC_AND_LOAD_H
    CALL INC_AND_LOAD_H
    CALL INC_AND_LOAD_H
    CALL INC_AND_LOAD_H
    CALL INC_AND_LOAD_H
    CALL INC_AND_LOAD_H
    CALL INC_AND_LOAD_H
    CALL SETBACK_HL
    RET

MR_CIRCLE:
    LD A, %11111100
    DEC H
    CALL INC_AND_LOAD_H
    LD A, %11111110
    CALL INC_AND_LOAD_H
    CALL INC_AND_LOAD_H
    CALL INC_AND_LOAD_H
    CALL INC_AND_LOAD_H
    CALL INC_AND_LOAD_H
    CALL INC_AND_LOAD_H
    LD A, %11111100
    CALL INC_AND_LOAD_H
    CALL SETBACK_HL
    RET

LL_CIRCLE:
    LD A, %00111111
    LD (HL), A
    CALL INC_AND_LOAD_H
    LD A, %00011111
    CALL INC_AND_LOAD_H
    LD A, %00001111
    CALL INC_AND_LOAD_H
    LD A, %00000111
    CALL INC_AND_LOAD_H
    LD A, %00000011
    CALL INC_AND_LOAD_H
    LD A, %00000000
    CALL INC_AND_LOAD_H
    CALL INC_AND_LOAD_H
    CALL SETBACK_HL
    RET

LM_CIRCLE:
    LD A, %11111111
    DEC H
    CALL INC_AND_LOAD_H
    CALL INC_AND_LOAD_H
    CALL INC_AND_LOAD_H
    CALL INC_AND_LOAD_H
    CALL INC_AND_LOAD_H
    CALL INC_AND_LOAD_H
    LD A, %01111110
    CALL INC_AND_LOAD_H
    LD A, %00000000
    CALL INC_AND_LOAD_H
    CALL SETBACK_HL
    RET

LR_CIRCLE:
    LD A, %11111100
    LD (HL), A
    CALL INC_AND_LOAD_H
    LD A, %11111000
    CALL INC_AND_LOAD_H
    LD A, %11110000
    CALL INC_AND_LOAD_H
    LD A, %11100000
    CALL INC_AND_LOAD_H
    LD A, %11000000
    CALL INC_AND_LOAD_H
    LD A, %00000000
    CALL INC_AND_LOAD_H
    CALL INC_AND_LOAD_H
    CALL SETBACK_HL
    RET

INC_AND_LOAD_H:
    LD DE, BC
    LD BC, $0100
    ADD HL, BC
    LD (HL), A
    LD BC, DE
    RET

SETBACK_HL:
    LD DE, BC
    LD BC, $F901
    ADD HL, BC
    LD BC, DE
    RET

INC_HL_3X3:
    PUSH AF: PUSH BC: PUSH DE
    LD (HL), A
    LD DE, BC
    INC HL
    LD (HL), A
    INC HL
    LD (HL), A
    LD BC, 30
    ADD HL, BC
    POP DE: POP BC: POP AF
    RET

SET_C_COLOR_E:
    LD A, 1*8+7
    CALL INC_HL_3X3
    CALL INC_HL_3X3
    CALL INC_HL_3X3
    RET

CONVERT_58_2_40 ; CONVIERTE UNA DIRECCION DE MEMORIA QUE COMIENZA CON $58XX A $40XX
    LD BC, $E800
    ADD HL, BC
    RET